# Generated by Django 5.2.13 on 2026-04-27 08:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_service', '0001_initial'),
    ]

    operations = [

    # 1. Rename FIRST
    migrations.RenameModel(
        old_name='Model',
        new_name='Feature',
    ),

    # 2. Then change table name
    migrations.AlterModelTable(
        name='feature',
        table='feature_registry',
    ),

    # 3. Remove constraints safely
    migrations.AlterUniqueTogether(
        name='usermodelpermission',
        unique_together=None,
    ),

    migrations.RemoveField(
        model_name='usermodelpermission',
        name='model',
    ),

    # 4. Create new models
    migrations.CreateModel(
        name='OrganizationFeatureAccess',
        fields=[
            ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ('organization_id', models.UUIDField(db_index=True)),
            ('is_active', models.BooleanField(default=True)),
            ('feature', models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='organization_accesses',
                to='model_service.feature'
            )),
        ],
        options={
            'db_table': 'organization_feature_accesses',
            'unique_together': {('organization_id', 'feature')},
        },
    ),

    migrations.CreateModel(
        name='UserFeaturePermission',
        fields=[
            ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ('user_id', models.UUIDField(db_index=True)),
            ('can_read', models.BooleanField(default=False)),
            ('can_write', models.BooleanField(default=False)),
            ('can_delete', models.BooleanField(default=False)),
            ('feature', models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='user_permissions',
                to='model_service.feature'
            )),
        ],
        options={
            'db_table': 'user_feature_permissions',
            'unique_together': {('user_id', 'feature')},
        },
    ),

    # 5. Delete old models LAST
    migrations.DeleteModel(name='OrganizationModelAccess'),
    migrations.DeleteModel(name='UserModelPermission'),
]